<?xml version="1.0"?>
<robot name="sensor_stick" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.14159"/>
  <xacro:property name="mass1" value="10" />
  <xacro:property name="mass2" value="1" />
  <xacro:property name="width1" value="0.1" /> <!--link_1 radius-->
  <xacro:property name="width2" value="0.1" /> <!--link_2 radius-->
  <xacro:property name="length0" value="0.1" /> <!--link_1 length-->
  <xacro:property name="length1" value="1.0" /> <!--link_2 length-->
  <xacro:property name="length2" value="0.1" /> <!--link_3 length-->
  <xacro:property name="mass_camera" value="0.2" />

  <!--Import gazebo elements-->
  <!-- <xacro:include filename="$(find lidar_world)/urdf/sensor_stick.gazebo.xacro" /> -->
  <xacro:include filename="$(find lidar_world)/urdf/sensor_stick_gpu.gazebo.xacro" />

  <!--Links-->
  <link name="world"/>

  <link name="link_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${width1} ${length1}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${width1} ${length1}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass1}"/>
      <inertia
        ixx="${mass1 / 12.0 * (width1*width1 + length1*length1)}" ixy="0.0" ixz="0.0"
        iyy="${mass1 / 12.0 * (length1*length1 + width1*width1)}" iyz="0.0"
        izz="${mass1 / 12.0 * (width1*width1 + width1*width1)}"/>
    </inertial>
  </link>

  <link name="link_2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${width2} ${length2}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${width2} ${length2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
        ixx="${mass2 / 12.0 * (width2*width2 + length2*length2)}" ixy="0.0" ixz="0.0"
        iyy="${mass2 / 12.0 * (length2*length2 + width2*width2)}" iyz="0.0"
        izz="${mass2 / 12.0 * (width2*width2 + width2*width2)}"/>
    </inertial>
  </link>

  <!-- velodyne lidar -->
  <link name="velodyne_base_link">
    <inertial>
      <mass value="0.83"/>
      <origin xyz="0 0 0.03585"/>
      <inertia ixx="0.000908059425" ixy="0" ixz="0" iyy="0.000908059425" iyz="0" izz="0.0011049624"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="$(find lidar_world)/meshes/VLP16_base_1.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.03585"/>
      <geometry>
        <cylinder length="0.0717" radius="0.0516"/>
      </geometry>
    </collision>
  </link>
  <link name="velodyne">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.0377"/>
      <geometry>
        <mesh filename="$(find lidar_world)/meshes/VLP16_scan.dae"/>
      </geometry>
    </visual>
  </link>
  <link name="velodyne_top">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.0377"/>
      <geometry>
        <mesh filename="$(find lidar_world)/meshes/VLP16_base_2.dae"/>
      </geometry>
    </visual>
  </link>

  <!--Joints-->
  <joint name="fixed_base_joint" type="fixed">
    <parent link="world"/>
    <child link="link_1"/>
    <origin xyz="0 0 ${length1/2+0.1}" rpy="0 0 0"/>
  </joint>

  <joint name="pan_joint" type="fixed">
    <parent link="link_1"/>
    <child link="link_2"/>
    <!-- <axis xyz="0 0 1"/> -->
    <origin xyz="0 0 ${length1/2+length2/2}" rpy="0 0 0"/>
  </joint>

  <joint name="velodyne_base_mount_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${length2/2}"/>
    <parent link="link_2"/>
    <child link="velodyne_base_link"/>
  </joint>

  <joint name="velodyne_base_scan_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.0377"/>
    <parent link="velodyne_base_link"/>
    <child link="velodyne"/>
  </joint>

  <joint name="velodyne_top_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="velodyne"/>
    <child link="velodyne_top"/>
  </joint>

</robot>