<?xml version="1.0"?>
<robot name="basic_stick" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.14159"/>
  <xacro:property name="mass1" value="10" />
  <xacro:property name="mass2" value="1" />
  <xacro:property name="width1" value="0.1" /> <!--link_1 radius-->
  <xacro:property name="width2" value="0.1" /> <!--link_2 radius-->
  <xacro:property name="length0" value="0.1" /> <!--link_1 length-->
  <xacro:property name="length1" value="1.5" /> <!--link_2 length-->
  <xacro:property name="length2" value="0.1" /> <!--link_3 length-->
  <xacro:property name="mass_camera" value="0.2" />


  <!--Links-->
  <link name="world"/>

  <link name="link_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${width1} ${length1}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${width1} ${length1}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass1}"/>
      <inertia
        ixx="${mass1 / 12.0 * (width1*width1 + length1*length1)}" ixy="0.0" ixz="0.0"
        iyy="${mass1 / 12.0 * (length1*length1 + width1*width1)}" iyz="0.0"
        izz="${mass1 / 12.0 * (width1*width1 + width1*width1)}"/>
    </inertial>
  </link>

  <link name="link_2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${width2} ${length2}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${width2} ${length2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
        ixx="${mass2 / 12.0 * (width2*width2 + length2*length2)}" ixy="0.0" ixz="0.0"
        iyy="${mass2 / 12.0 * (length2*length2 + width2*width2)}" iyz="0.0"
        izz="${mass2 / 12.0 * (width2*width2 + width2*width2)}"/>
    </inertial>
  </link>

  <!--Joints-->
  <joint name="fixed_base_joint" type="fixed">
    <parent link="world"/>
    <child link="link_1"/>
    <origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
  </joint>

  <joint name="pan_joint" type="fixed">
    <parent link="link_1"/>
    <child link="link_2"/>
    <!-- <axis xyz="0 0 1"/> -->
    <origin xyz="0 0 ${length1/2+length2/2}" rpy="0 0 -${pi/2}"/>
  </joint>

</robot>